### ISSUE TITLE
Data Set unavailable

### ISSUE THREAD

**Issue by jimmy-walker** [DaniloSorano/PassNet#8]
Appreciate for your paper and code. But the url of dataset is unavailable. 
https://doi.org/10.6084/m9.figshare.c.5036993
Could you update it?
Thanks

**Comment by jhwang7628** [comment]
second this. The dataset is still not available.

**Comment by jonpappalord** [comment]
Hi, look at the ReadMe in the repository: https://github.com/jonpappalord/PassNet, you should find the links to download the data.
Luca

**Comment by jhwang7628** [comment]
well, so this link is in the README: https://doi.org/10.6084/m9.figshare.c.5036993
and it says "the page cannot be found". Am I looking at the wrong link?
![image](https://user-images.githubusercontent.com/7445300/98457524-1e4cbf80-213d-11eb-9513-3305807c3878.png)
